### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by olive13400** [okigan/awscurl#107]
Hi
I just tested but
I run a Centos 6.10, python 3.6

 ~/test/testV2/awscurl-0.21/awscurl
$ ./awscurl.py --service s3 https://awscurl-sample-bucket.s3.amazonaws.com
Traceback (most recent call last):
  File "./awscurl.py", line 19, in <module>
    from .utils import sha256_hash, sha256_hash_for_binary_data, sign
ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package

May you help me?

regards

**Comment by okigan** [comment]
Interesting -- I don't have CentOs as test target maybe because of that?

Have you tried running through docker as shown in readme file?

**Comment by okigan** [comment]
@olive13400 i've just added ci-in-docker.sh file that would very builds and test in ubuntu and centos -- all test when I run it. please verify (build takes a while) that it passes on your system too.

**Comment by okigan** [comment]
@olive13400 bumping up the thread to avoid it going cold/closed.
