### ISSUE TITLE
download/clone version is different from pip install

### ISSUE THREAD

**Issue by TechieGary** [okigan/awscurl#12]
pip install does not included --profile parameters

**Comment by okigan** [comment]
Good catch. 

I'll follow up.

**Comment by okigan** [comment]
Latest is now published as version 0.8: https://pypi.python.org/pypi?:action=display&name=awscurl&version=0.8

@TechieGary give pypi couple hours and try install/upgrade again. Comment here when you get the right version

**Comment by TechieGary** [comment]
Tried —upgrade and install. still 0.6, but will try again later.

Thanks buddy!!

**Comment by okigan** [comment]
Works now: 

`
pip install awscurl
....
Successfully installed awscurl-0.8
`
