### ISSUE TITLE
Proposal: Allow modifying signature hostname 

### ISSUE THREAD

**Issue by speller** [okigan/awscurl#129]
I'm trying to run awscurl to perform requests to the ES service through an SSH tunnel. The tunnel opens a local port connected to the ES service 443 port on the API endpoint. The tunnel is required to connect to a service not available to the public. The issue is that awscurl creates a signature using the URL passed in CLI. But the service hostname and port are different from the local URL. I need to make a signature using the real API endpoint, not using the local one. It would be nice to add this feature.

**Comment by speller** [comment]
Answering my own question - it's possible to do with the `host` header passed. But the only issue is that the header name must be lower-case. This will not work: `-H "Host: $ES_HOST"`.

**Comment by speller** [comment]
Also, documenting this would be very helpful.

**Comment by okigan** [comment]
I think I’ve heard of something similar. 

Is that the same as specifying HOST header (different than hostname in the url)?

**Comment by speller** [comment]
> I think I’ve heard of something similar. Is that the same as specifying HOST header (different than hostname in the URL)?

Yes, the same. I just described why I need that. My actual URL passed to awscurl is something like `https://host.docker.internal:10443`. But the signature must be created for the real service API endpoint hostname.

**Comment by speller** [comment]
Another minor suggestion: don't include the 443 port to the hostname to use in the signature if it was explicitly specified along with the https protocol. Using `vpc-***.***.es.amazonaws.com:443` as the hostname in the signature cause validation failure.

**Comment by okigan** [comment]
Could you start a PR as section in the readme.md file - I’ll take it from there. 

Thanks!

**Comment by okigan** [comment]
Are you using latest version? I remember adding case insensitive logic before.

**Comment by okigan** [comment]
Hmm, seems it’s a thing todo. Similar to: https://github.com/aws/aws-cli/issues/2883

**Comment by speller** [comment]
> Are you using latest version? I remember adding case insensitive logic before.

I'm using the latest version in the Docker container.

**Comment by okigan** [comment]
@speller review the above please

**Comment by okigan** [comment]
@speller Bumping up old thread. Would you review the above for the upcoming release?

**Comment by okigan** [comment]
Branch merged -- closing issue.
