### ISSUE TITLE
urllib's InsecureRequestWarning printed to stdout when using the --insecure parameter

### ISSUE THREAD

**Issue by speller** [okigan/awscurl#130]
I'm using a custom hostname for the URL and thus the server certificate can't be verified. I'm passing the `--insecure` argument but it still prints the following warning:

```
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
```

I think this should be suppressed.

**Comment by okigan** [comment]
@speller please confirm latest resolves your issue (ex. installing from source: $ pip install git+https://github.com/okigan/awscurl)

**Comment by speller** [comment]
@okigan this seems to be not merged yet to the main branch?

**Comment by okigan** [comment]
Done

**Comment by speller** [comment]
OK, thank you.
