### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by maxmanders** [okigan/awscurl#141]
Not an issue, feel free to close. I just wanted to say thank you for this tool. Had a sticky situation with ElasticSearch today, and awscurl came to the rescue. Thank you!

**Comment by okigan** [comment]
Great news to hear!

**Comment by johannes-gehrs** [comment]
100% correct your tool is a staple of our daily work and has never failed us. Thank you so much for your work.

**Comment by maxmanders** [comment]
Closing to avoid noise in the list of legit issues :-)
