### ISSUE TITLE
raise_for_request should not be used for non-successful response

### ISSUE THREAD

**Issue by stephenmuss** [okigan/awscurl#152]
Hi there,

I'm wondering why you elected to use `response.raise_for_status()` after receiving the response - https://github.com/okigan/awscurl/blob/184d7735b57d5c71f75f52a85cc8c8909226b6d5/awscurl/awscurl.py#L537

Would it not make more sense to return an exit code that is either 0 for a successful request or non-zero for a non-successful request?

This would mean tools such as jq etc could still parse the response without the Python traceback interfering where a non-successful status code may still be anticipated.

Happy to open a PR if it makes sense.

**Comment by okigan** [comment]
Thanks for looking into it. If I recall intent was that `raise_for_status()` would raise an exception which would cause a different return code

**Comment by stephenmuss** [comment]
I'm happy to open a PR if you are amenable to that.

**Comment by okigan** [comment]
Yes, PR would be great!

I had a quick look at [response.ok](https://github.com/psf/requests/blob/d09659997cd1e3eca49a07c59ece5557071c0ab9/requests/models.py#L702-L715) and looks like it also calls [raise_for_status](https://github.com/psf/requests/blob/d09659997cd1e3eca49a07c59ece5557071c0ab9/requests/models.py#L712) which would still produce the output you'd like to avoid? Something similar to [this](https://github.com/certbot/certbot/blob/399b932a869403b142fb0271aec510614085d6ed/certbot/certbot/_internal/eff.py#L108) could get the behavior you are looking for.

Again, thanks for looking into this.

**Comment by stephenmuss** [comment]
Thanks @okigan. I have opened a PR in #153 with an explanation of why `response.ok` is still sufficient. Thanks for being open to the PR and even more thanks for the very handy tool you've written.
