### ISSUE TITLE
Request: Support for Container credentails

### ISSUE THREAD

**Issue by misirlou-tg** [okigan/awscurl#164]
ECS containers have different environment variables for their credentials. This is described in the following:
[Container credential provider](https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html)

The link says that there is support for this in the AWS SDK for Python, I don't know how difficult this would be in implement in awscurl.

There is an easy way to see this in action, the CloudShell available in the AWS console has the environment variables described in the above link (`$AWS_CONTAINER_AUTHORIZATION_TOKEN`, `$AWS_CONTAINER_CREDENTIALS_FULL_URI`). Awscurl works in the CloudShell currently, I copy/paste my credential environment variables into it, but mine expire after 1hr, so using the container's credentials would help a lot.

Thanks for your work on this utility!

**Comment by okigan** [comment]
Try the latest release. Here is [example](https://github.com/okigan/awscurl/issues/163#issuecomment-1536535837) when using Cloudshell.

**Comment by misirlou-tg** [comment]
Excellent, that fixed it! I updated to the 0.28 release and it is working in CloudShell with my credentials.
