### ISSUE TITLE
Use AWS_SESSION_TOKEN instead of custom AWS_SECURITY_TOKEN env variable by default

### ISSUE THREAD

**Issue by robertoandrade** [okigan/awscurl#19]
The [AWS documentation](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) for the environment variables that specify credential components for their own `aws` cli specify that the STS tokens may be exposed via a `AWS_SESSION_TOKEN` environment variable.

The `awscurl` though expects the value in a different environment variable named `AWS_SECURITY_TOKEN`. I believe it should use the same environment variable as the Amazon CLI.

**Comment by okigan** [comment]
agree, that should be made consistent -- I'll review.

**Comment by jonathancartwright** [comment]
I have a change in my fork that pulls the AWS_SESSION_TOKEN from the .aws/credentials file if it is present.  this behavior is similar to what you already do for the other types of tokens. 

I know that this would be really helpful for people that use STS tokens.  Please let me know if you would like me to issue a PR for review.  my fork is at https://github.com/jonathancartwright/awscurl if you want to look at that before having me PR.

**Comment by okigan** [comment]
Looks good -- looking forward to PR.

**Comment by okigan** [comment]
https://github.com/okigan/awscurl/pull/30 merged
