### ISSUE TITLE
Homebrew package does not install botocore

### ISSUE THREAD

**Issue by if-jeremy** [okigan/awscurl#192]
When trying to use awscurl installed on MacOS via Homebrew, in conjunction with aws-vault and it's --ecs-server option, I found that Homebrew does not install botocore due to it being listed as "extras_require" in setup.py.  See:

https://github.com/Homebrew/homebrew-core/issues/155202

I think that botocore should either be moved to install_requires, or an update to the README.md file be made to indicate that Homebrew-installed versions do not include this support.

**Comment by okigan** [comment]
releases post v0.34 shall install botocore, please re-open if still run into this issue
