### ISSUE TITLE
Feature Request: Proxy Support

### ISSUE THREAD

**Issue by cyberitech** [okigan/awscurl#212]
I would like to be able to set a proxy directly with `awscurl`.  I often import the `make_request` function into various code I use, and only want `awscurl` itself to be proxied, and maybe only on specific requests.

Currently, if I want to proxy `awscurl` I wrap it in environment variables
```
os.environ["HTTPS_PROXY"] = "https://some_proxy."
r = make_request(**kwargs)
del os.environ["HTTPS_PROXY"]
```

The issue here is that this is not thread safe.  If i have multiple threads of `awscurl` running, it complicates this process requiring additional boilerplate code to turn the operations that set/delete an environment variable into thread-safe equivalents.

having a native way to specify a proxy in the `awscurl` kwargs would be ideal.

**Comment by okigan** [comment]
Reference: https://everything.curl.dev/usingcurl/proxies/http.html
