### ISSUE TITLE
A release with print-content-as-text?

### ISSUE THREAD

**Issue by tomfaulhaber** [okigan/awscurl#32]
It looks like the current pypi version of this package (0.11) still has "print(r.content)". I was using this with Amazon SageMaker and the results were coming back as a byte array ("b'...'") instead of text. When I do a git clone and run the latest version, it works great.

Could we get a pypi release of the latest version? Thanks!

(P.S. thanks for this really useful tool)

**Comment by okigan** [comment]
@tomfaulhaber thanks for feedback, latest code is published as version 0.12 on pypi: https://pypi.python.org/pypi/awscurl/0.12
