### ISSUE TITLE
URI encoding

### ISSUE THREAD

**Issue by mbayrak78** [okigan/awscurl#33]
Hi,

please update awscurl in order to allow non URL encoded charecters.
E.g. 
`GET <host>/_task/taskId:123:abc`

the character ":" is not RFC conform and must be URL encoded.
I would recommend to change line 182 as:

`
requests.utils.quote(canonical_uri)
`

If URI is not encoded properly AWS returns an error indicating that signature check has failed.
If you change request to:
`GET <host>/_task/taskId%3A123%3Aabc `

AWS tries to validate against
`GET <host>/_task/taskId%253A123%253Aabc `

So AWS encodes the char % separately to %25.

BR
MB

**Comment by okigan** [comment]
I think this should be a bit more specific as URL path quoting is different than query parameter quoting. 

@mbayrak78 could you start a pull request on this?

**Comment by mbayrak78** [comment]
As described here:
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html and
https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html#canonical-request
the canonical URI must be URI-encoded.
