### ISSUE TITLE
Return of make_request

### ISSUE THREAD

**Issue by mbayrak78** [okigan/awscurl#34]
Hi,

would it be possible to return the response object instead of returning a number (0, 1, etc.) for the success status of the request?
The reason behind that is, if one e.g. performs a GET with awscurl, it would be nice to have the response body available for further usage. Currently it is only piped to print() whcih is useless for automation...

BR & thanks
MB

**Comment by okigan** [comment]
I guess status code processing can be pulled up -- can you add more context how are you using this for automation and/or what services you are automating.

**Comment by mbayrak78** [comment]
Sure, we use awscurl in our CD/CI pipelines to automate build and integration process via scripting (sh, python).
In one of this automation steps we make an HTTP GET request. The server response with useful information that we want to use furthermore in the scripts, e.g.:

``` python
from awscurl.awscurl import 
...
var params = {...}
status = make_request(params) 

# status is 0 or 1 returned by the inner call : return send_request(uri, data, headers, method)
# it would be better if we could have the respsonse object: response = make_request(...)
# then we could use if(response.status_code == 200) or JSON.parse(response.text)
```

**Comment by okigan** [comment]
feature branch: https://github.com/okigan/awscurl/tree/feature/issues/34

**Comment by okigan** [comment]
@mbayrak78 have a look at the PR: https://github.com/okigan/awscurl/pull/37 let me know if you see any issues if it does/not covers your use-case

**Comment by mbayrak78** [comment]
Hi Igor,

thanks for the changes.
Returning the response object to the caller fits our needs perfectly and I guess would also enhance others use case too.

BR

**Comment by okigan** [comment]
merged
