### ISSUE TITLE
awscurl in python script ?

### ISSUE THREAD

**Issue by dragan979** [okigan/awscurl#41]
is it possible to put it in python script: run command and get output to JSON file (without subprocess)

```
import requests

headers = {
    'Content-Type': 'application/json',
}
params = (
    ('Action', 'ListUsers'),
    ('Version', '2010-05-08'),
)
response = requests.get('https://iam.amazonaws.com/', headers=headers, params=params)
with open('1.json', 'w') as outfile:
    outfile.write(response.content)
```
and getting 

```
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>MissingAuthenticationToken</Code>
    <Message>Request is missing Authentication Token</Message>
  </Error>
  <RequestId>bb3695a3-399f-11e8-b6b6-17d7b8ab932d</RequestId>
</ErrorResponse>
```

**Comment by okigan** [comment]
@dragan979 check out recent changes to awscurl (not published yet on pipi) to which makes 'make_request' function public -- you could use that in your script. Try that and post your feedback here.

**Comment by dragan979** [comment]
`./awscurl.py --service iam 'https://iam.amazonaws.com/?Action=ListUsers&Version=2010-05-08'`
returns data, how to write output to json and call code above from python script, or how to embed parameters into awscurl.py ?

**Comment by dragan979** [comment]
awscurl.py works, how, using python code to write json output, i managed to substitute uri inside a script, but have issues doing same for service (iam)

**Comment by okigan** [comment]
@dragan979 checkout more info how to use python modules: https://docs.python.org/2/tutorial/modules.html

you should be able to get latest awscurl version and import it and use `make_request()` with your parameters, similar to: https://github.com/okigan/awscurl/blob/master/awscurl/awscurl.py#L336

**Comment by dragan979** [comment]
@okigan , i only have 2 parameters:service and uri, i hardcoded uri just need same for service (if it's possible) i'm beginner in python

**Comment by dragan979** [comment]
@okigan, found alternative; boto3, works like a charm
