### ISSUE TITLE
AWS_SESSION_TOKEN not taken in account

### ISSUE THREAD

**Issue by scraly** [okigan/awscurl#46]
Hi,

it seems that awscurl is not taking in account AWS_SESSION_TOKEN environment variable (when an user is assuming a role, in order to have some rights).

Is it possible to calculate the aws signature version 4 with this AWS_SESSION_TOKEN instead of only with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY?

Without taking in account this environment variable (created dynamically when an user is assuming a role), we obtain a 403 http error code.

Thanks

**Comment by okigan** [comment]
Closing - believed to be resolved and due to inactivity
