### ISSUE TITLE
Exception occurred with v0.18 in python 2.7 & python 3.7.1

### ISSUE THREAD

**Issue by mbayrak78** [okigan/awscurl#78]
Hi,

we just tried to use v0.18 and got this exception:

Traceback (most recent call last):
  File "/usr/local/bin/awscurl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awscurl/awscurl.py", line 491, in main
    print(response.headers.encode('utf-8'), end='\n\n')
AttributeError: 'CaseInsensitiveDict' object has no attribute 'encode'

**Comment by okigan** [comment]
@mbayrak78, please try the bugfix release v0.19

**Comment by mbayrak78** [comment]
@okigan thanks for the quick bug fix. v0.19 tested and it works +1
