### ISSUE TITLE
Publish awscurl to homebrew

### ISSUE THREAD

**Issue by KieranHunt** [okigan/awscurl#82]
It'd be nice to be able to grab `awscurl` via homebrew.

For instructions, see: https://docs.brew.sh/Formula-Cookbook

**Comment by okigan** [comment]
@KieranHunt could you give some examples of other *python* tools that get installed with homebrew? -- I am trying to get a clear picture for this proposal vs homebrew install python, then pip install awscurl

**Comment by okigan** [comment]
@KieranHunt hmm, see this comment, need some help on that: https://github.com/okigan/homebrew-core/pull/2/files#diff-c308bc5e97cfdf7d46e9587e812da610R47

**Comment by KieranHunt** [comment]
> @KieranHunt could you give some examples of other _python_ tools that get installed with homebrew? -- I am trying to get a clear picture for this proposal vs homebrew install python, then pip install awscurl
> 
> relevant links:
> 
>     * https://www.stickyminds.com/article/brew-vs-pip-which-package-installer-should-you-use

I went through some of [this list](https://hugovk.github.io/top-pypi-packages/) of the top packages on PyPI. Most were libraries rather than command line tools though.

I see the `awscli` there: https://formulae.brew.sh/formula/awscli
Here's it's formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb

**Comment by okigan** [comment]
I've got it more forward but I am stuck how to get dependencies installed. 

See PR: https://github.com/Homebrew/homebrew-core/pull/47715

but calling `brew install --build-from-source Formula/awscurl.rb` fails when dependencies are uncommented in the awscurl.rb. 

So this needs more help there (as I do not have enough exposure to this) @KieranHunt can you move it from here?

**Comment by KieranHunt** [comment]
I've never done this before either but I'll see what I can do, @okigan. I'll see how much of the `awscli` formula I can ~~copy~~ learn from.

**Comment by okigan** [comment]
yes, that formula seems relevant. I've bootstrapped with following script: https://github.com/okigan/awscurl/blob/feature/homebrew-template-generator/pybrew.sh. 

if all pans out this should run successfully

```
brew install --build-from-source Formula/awscurl.rb 
awscurl --help
```

**Comment by okigan** [comment]
@KieranHunt bumping this up -- any updates (would be cool to finish this as new year present)

**Comment by KieranHunt** [comment]
Hey sorry for ghosting for a while 👻
Busy last week at work for the year.

I'm not having much success with your commands there. But I'm also running this using Linuxbrew.

```
$ git clone https://github.com/okigan/homebrew-core.git
Cloning into 'homebrew-core'...
remote: Enumerating objects: 662434, done.
remote: Total 662434 (delta 0), reused 0 (delta 0), pack-reused 662434
Receiving objects: 100% (662434/662434), 268.34 MiB | 30.30 MiB/s, done.
Resolving deltas: 100% (432322/432322), done.

$ cd homebrew-core

$ brew install --build-from-source Formula/awscurl.rb
Updating Homebrew...

<snip> bunch of formulae being updated </snip>

Error: No available formula with the name "Formula/awscurl.rb"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```

But if it seems to be working for you will you open a PR? Or whatever their process is.

**Comment by okigan** [comment]
They have not merged my pr yet 

Do git checkout of my branch then it should work. Get branch name from here https://github.com/Homebrew/homebrew-core/pull/48129

**Comment by okigan** [comment]
@KieranHunt the new year gift of awscurl in homebrew is here : https://github.com/Homebrew/homebrew-core/pull/48129

standard installation shall work: `brew install awscurl`

**Comment by KieranHunt** [comment]
Oh fantastic! Thank you so much.

I see they're pretty strict with their pull requests so thanks for all of your effort. ✨
