### ISSUE TITLE
Installing awscurl broke git-remote-codecommit

### ISSUE THREAD

**Issue by jimmone** [okigan/awscurl#91]
After installing awscurl git-remote-codecommit stopped working and I cannot get it to work again. When I try to do `git pull `for example I get the following error message: `fatal: unable to find remote helper for 'codecommit'`.

**Comment by okigan** [comment]
That’s odd - awscurl does not have any git related dependencies so should not affect it. 

Can you reproduce the issue?

**Comment by jimmone** [comment]
I reinstalled python, git-remote-codecommit and awscurl and now everything is working fine.
